TodoList/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace TodoList.Models;

public class Category
{
    [Key] public int Id {
        get;
        set;
    }

    public string Title { get; set; } = string.Empty;
    public ICollection<Todo> Todos { get; set; }
}

TodoList/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace TodoList.Models;

public class Department
{
    [Key] public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public ICollection<User> Users { get; set; }
}

TodoList/Models/ErrorViewModel.cs
namespace TodoList.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TodoList/Models/Todo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TodoList.Models;

public class Todo
{
    [Key] public int Id { get; set; }
    public required string Title { get; set; }
    [ForeignKey("CategoryId")]
    public int CategoryId { get; set; }
    public required Category Category { get; set; }
    [ForeignKey("UserId")]
    public int UserId { get; set; }
    public required User User { get; set; }
}

TodoList/Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TodoList.Models;

public class User
{
    [Key] public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public ICollection<Todo> Todos { get; set; }
    [ForeignKey("DepartmentId")]
    public int DepartmentId { get; set; }
    public Department Department { get; set; }
}

TodoList/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.Data;
using TodoList.Models;

namespace TodoList.Controllers;

public class CategoryController : Controller
{
    private readonly DatabaseContext _database;

    public CategoryController(DatabaseContext database)
    {
        _database = database;
    }
    
    [HttpPost]
    public IActionResult CreateCategory(Category category)
    {
        
        _database.Categories.Add(category);
        _database.SaveChanges();
        ViewBag.Categories = _database.Categories.ToList();
        return RedirectToAction("ListCategories");
    }
    
    public IActionResult ListCategories()
    {
        return View(_database.Categories.ToList());
    }
    
    public IActionResult CreateCategory()
    {
        
        return View();
    }
}

TodoList/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.Data;
using TodoList.Models;

namespace TodoList.Controllers;

public class DepartmentController : Controller
{
    private readonly DatabaseContext _database;

    public DepartmentController(DatabaseContext database)
    {
        _database = database;
    }
    
    [HttpPost]
    public IActionResult CreateDepartment(Department department)
    {
        
        _database.Departments.Add(department);
        _database.SaveChanges();
        ViewBag.Departements = _database.Departments.ToList();
        return RedirectToAction("ListDepartments");
    }
    
    public IActionResult ListDepartments()
    {
        return View(_database.Departments.ToList());
    }
    
    public IActionResult CreateDepartment()
    {
        
        return View();
    }
}

TodoList/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TodoList.Models;

namespace TodoList.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

TodoList/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TodoList.Data;
using TodoList.Models;

namespace TodoList.Controllers;

public class TodoController : Controller
{
    private readonly DatabaseContext _database;

    public TodoController(DatabaseContext database)
    {
        _database = database;
    }
    
    public IActionResult CreateTodo()
    {
        ViewData["UserId"] = new SelectList(_database.Users, "Id", "Name");
        ViewData["CategoryId"] = new SelectList(_database.Categories, "Id", "Title");
        return View();
    }

    public IActionResult ListTodos()
    {
        return View(_database.Todos.Include(t => t.User).Include(t=>t.Category).ToList());
    }

    [HttpPost]
    public IActionResult CreateTodo(Todo todo)
    {
            _database.Todos.Add(todo);
            _database.SaveChanges();
        ViewBag.Users = _database.Users.ToList();
        ViewBag.Categories = _database.Categories.ToList();
            return RedirectToAction("ListTodos");
    }
    
}

TodoList/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TodoList.Data;
using TodoList.Models;

namespace TodoList.Controllers;

public class UsersController : Controller
{
    private readonly DatabaseContext _database;

    public UsersController(DatabaseContext database)
    {
        _database = database;
    }

    [HttpPost]
    public IActionResult CreateUser(User user)
    {
        
            _database.Users.Add(user);
            _database.SaveChanges();
            ViewBag.Departements = _database.Departments.ToList();
            return RedirectToAction("ListUsers");
    }
    
    public IActionResult ListUsers()
    {
        return View(_database.Users.Include(u=>u.Department).ToList());
    }

    public IActionResult CreateUser()
    {
        ViewData["DepartmentId"] = new SelectList(_database.Departments, "Id", "Name");
        return View();
    }

}

TodoList/Views/Category/CreateCategory.cshtml
@model Category

@{
    ViewData["Title"] = "Create Category";
}

<h1>Create Category</h1>

<form asp-action="CreateCategory">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

TodoList/Views/Category/ListCategories.cshtml
@model IEnumerable<Category>

@{
    ViewData["Title"] = "List Categories";
}

<h1>Categories</h1>

<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Title</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var category in Model)
    {
        <tr>
            <td>@category.Id</td>
            <td>@category.Title</td>
        </tr>
    }
    </tbody>
</table>

TodoList/Views/Department/CreateDepartment.cshtml
@model Department

@{
    ViewData["Title"] = "Create Department";
}

<h1>Create Department</h1>

<form asp-action="CreateDepartment">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

TodoList/Views/Department/ListDepartments.cshtml
@model IEnumerable<Department>

@{
    ViewData["Title"] = "List Departments";
}

<h1>Departments</h1>

<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var department in Model)
    {
        <tr>
            <td>@department.Id</td>
            <td>@department.Name</td>
        </tr>
    }
    </tbody>
</table>

TodoList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    
    
</div>

TodoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TodoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TodoList.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TodoList</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="ListUsers">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="CreateUser">CreateUser</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="ListTodos">Todos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="CreateTodo">CreateTodo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="ListDepartments">Departments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="CreateDepartment">CreateDepartment</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="ListCategories">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="CreateCategory">CreateCategory</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - TodoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TodoList/Views/Todo/CreateTodo.cshtml
@model Todo

@{
    ViewData["Title"] = "Create Todo";
}

<h1>Create Todo</h1>

<form asp-action="CreateTodo">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="CategoryId">Category</label>
        @Html.DropDownListFor(m => m.CategoryId, ViewBag.Categories as SelectList, "Select a category")
    </div>
    <div class="form-group">
        <label asp-for="UserId">User</label>
        @Html.DropDownListFor(m => m.UserId, ViewBag.Users as SelectList, "Select a user")
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

TodoList/Views/Todo/ListTodos.cshtml
@model IEnumerable<Todo>

@{
    ViewData["Title"] = "List Todos";
}

<h1>Todos</h1>

<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Category</th>
        <th>User</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var todo in Model)
    {
        <tr>
            <td>@todo.Id</td>
            <td>@todo.Title</td>
            <td>@todo.Category.Title</td>
            <td>@todo.User.Name</td>
        </tr>
    }
    </tbody>
</table>

TodoList/Views/Users/CreateUser.cshtml
@model User

@{
    ViewData["Title"] = "Create User";
}

<h1>Create User</h1>

<form asp-action="CreateUser">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control">
    </div>
    
    <div class="form-group">
        <label asp-for="DepartmentId">Department</label>
        @Html.DropDownListFor(m => m.DepartmentId, ViewBag.Departments as SelectList, "Select a Department")
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

TodoList/Views/Users/ListUsers.cshtml
@model IEnumerable<User>

@{
    ViewData["Title"] = "List Users";
}

<h1>Users</h1>

<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Departments</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Id</td>
            <td>@user.Name</td>
            <td>@user.Department.Name</td>
        </tr>
    }
    </tbody>
</table>